//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.PushNotificationSettings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.PushNotificationSettings.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anti-noise settings.
        /// </summary>
        public static string AntiNoise_Header {
            get {
                return ResourceManager.GetString("AntiNoise_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Ticket Notifications.
        /// </summary>
        public static string BroadcastNotification_Header {
            get {
                return ResourceManager.GetString("BroadcastNotification_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delivery providers.
        /// </summary>
        public static string Delivery_Header {
            get {
                return ResourceManager.GetString("Delivery_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;TicketDesk is running demo mode. Push notifications are disabled.&lt;/p&gt;
        ///                            &lt;p&gt; To turn off demo mode, please change the setting in application configuration.&lt;/p&gt;.
        /// </summary>
        public static string DemoMode_Alert {
            get {
                return ResourceManager.GetString("DemoMode_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General settings.
        /// </summary>
        public static string General_Header {
            get {
                return ResourceManager.GetString("General_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Push notification settings.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a At least one provider must be enabled in order for messages to be sent..
        /// </summary>
        public static string RequiredProvider {
            get {
                return ResourceManager.GetString("RequiredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings saved!.
        /// </summary>
        public static string Saved_Alert {
            get {
                return ResourceManager.GetString("Saved_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save.
        /// </summary>
        public static string SaveOption {
            get {
                return ResourceManager.GetString("SaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Site Root Url.
        /// </summary>
        public static string SiteRootUrl {
            get {
                return ResourceManager.GetString("SiteRootUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This setting is vital to ensure that hyperlinks in emails contain the currect URL to your site..
        /// </summary>
        public static string SiteRootUrl_Help {
            get {
                return ResourceManager.GetString("SiteRootUrl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The url is invalid. If you are trying to use localhost for testing, specify the loopback IP address instead (http://127.0.0.1:80).
        /// </summary>
        public static string SiteRootUrl_Validation {
            get {
                return ResourceManager.GetString("SiteRootUrl_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Push Notification Settings.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use current root URL.
        /// </summary>
        public static string UseCurrentURL {
            get {
                return ResourceManager.GetString("UseCurrentURL", resourceCulture);
            }
        }
    }
}
