//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Domain {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Domain.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow users to edit priority?.
        /// </summary>
        public static string AllowInternalUsersToEditPriority {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow users to edit tags?.
        /// </summary>
        public static string AllowInternalUsersToEditTags {
            get {
                return ResourceManager.GetString("AllowInternalUsersToEditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow internal users to set the assigned to field (new ticket creation only)?.
        /// </summary>
        public static string AllowInternalUsersToSetAssigned {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Allow internal users to set or change the ticket owner?.
        /// </summary>
        public static string AllowInternalUsersToSetOwner {
            get {
                return ResourceManager.GetString("AllowInternalUsersToSetOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}: from &quot;{1}&quot; to &quot;{2}&quot;.
        /// </summary>
        public static string Changes_From_To {
            get {
                return ResourceManager.GetString("Changes_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Changes:.
        /// </summary>
        public static string Changes_Title {
            get {
                return ResourceManager.GetString("Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not authorized to perform this activity..
        /// </summary>
        public static string CheckSecurity_NotAuthorized {
            get {
                return ResourceManager.GetString("CheckSecurity_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a My Assigned.
        /// </summary>
        public static string DefaultListNameAssignedToMe {
            get {
                return ResourceManager.GetString("DefaultListNameAssignedToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket History.
        /// </summary>
        public static string DefaultListNameHistoryTickets {
            get {
                return ResourceManager.GetString("DefaultListNameHistoryTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a My Tickets.
        /// </summary>
        public static string DefaultListNameMyTickets {
            get {
                return ResourceManager.GetString("DefaultListNameMyTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Open Tickets.
        /// </summary>
        public static string DefaultListNameOpenTickets {
            get {
                return ResourceManager.GetString("DefaultListNameOpenTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report.
        /// </summary>
        public static string DefaultListNameReportTickets {
            get {
                return ResourceManager.GetString("DefaultListNameReportTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unassigned.
        /// </summary>
        public static string DefaultListNameUnassigned {
            get {
                return ResourceManager.GetString("DefaultListNameUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default New User Roles.
        /// </summary>
        public static string DefaultNewUserRoles {
            get {
                return ResourceManager.GetString("DefaultNewUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User is not authorized to create new tickets.
        /// </summary>
        public static string ExceptionSecurityUserCannotCreateNewTicket {
            get {
                return ResourceManager.GetString("ExceptionSecurityUserCannotCreateNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setting type conversion error: unable to convert SettingName [{0}] to specified SettingType [{1}].
        /// </summary>
        public static string ExceptionSettingsTypeConversionError {
            get {
                return ResourceManager.GetString("ExceptionSettingsTypeConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        public static string Project_Description {
            get {
                return ResourceManager.GetString("Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project Name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Categories.
        /// </summary>
        public static string SelectList_Categories {
            get {
                return ResourceManager.GetString("SelectList_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Priorities.
        /// </summary>
        public static string SelectList_Priorities {
            get {
                return ResourceManager.GetString("SelectList_Priorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket Types.
        /// </summary>
        public static string SelectList_TicketTypes {
            get {
                return ResourceManager.GetString("SelectList_TicketTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assign.
        /// </summary>
        public static string TicketActivity_Assign {
            get {
                return ResourceManager.GetString("TicketActivity_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel More Info.
        /// </summary>
        public static string TicketActivity_CancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_CancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string TicketActivity_Close {
            get {
                return ResourceManager.GetString("TicketActivity_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comment.
        /// </summary>
        public static string TicketActivity_Comment {
            get {
                return ResourceManager.GetString("TicketActivity_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        public static string TicketActivity_Create {
            get {
                return ResourceManager.GetString("TicketActivity_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Create.
        /// </summary>
        public static string TicketActivity_CreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivity_CreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        public static string TicketActivity_Edit {
            get {
                return ResourceManager.GetString("TicketActivity_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Attachments.
        /// </summary>
        public static string TicketActivity_EditAttachments {
            get {
                return ResourceManager.GetString("TicketActivity_EditAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force Close.
        /// </summary>
        public static string TicketActivity_ForceClose {
            get {
                return ResourceManager.GetString("TicketActivity_ForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Give Up.
        /// </summary>
        public static string TicketActivity_GiveUp {
            get {
                return ResourceManager.GetString("TicketActivity_GiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pass.
        /// </summary>
        public static string TicketActivity_Pass {
            get {
                return ResourceManager.GetString("TicketActivity_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Provide Info.
        /// </summary>
        public static string TicketActivity_ProvideInfo {
            get {
                return ResourceManager.GetString("TicketActivity_ProvideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-assign.
        /// </summary>
        public static string TicketActivity_ReAssign {
            get {
                return ResourceManager.GetString("TicketActivity_ReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Re-open.
        /// </summary>
        public static string TicketActivity_ReOpen {
            get {
                return ResourceManager.GetString("TicketActivity_ReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request More Info.
        /// </summary>
        public static string TicketActivity_RequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivity_RequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolve.
        /// </summary>
        public static string TicketActivity_Resolve {
            get {
                return ResourceManager.GetString("TicketActivity_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Take Over.
        /// </summary>
        public static string TicketActivity_TakeOver {
            get {
                return ResourceManager.GetString("TicketActivity_TakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a added comment.
        /// </summary>
        public static string TicketActivityAddComment {
            get {
                return ResourceManager.GetString("TicketActivityAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a assigned the ticket to {0}.
        /// </summary>
        public static string TicketActivityAssign {
            get {
                return ResourceManager.GetString("TicketActivityAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a has cancelled the request for more information.
        /// </summary>
        public static string TicketActivityCancelMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityCancelMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a closed the ticket.
        /// </summary>
        public static string TicketActivityClose {
            get {
                return ResourceManager.GetString("TicketActivityClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a created the ticket.
        /// </summary>
        public static string TicketActivityCreate {
            get {
                return ResourceManager.GetString("TicketActivityCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a created the ticket on behalf of {0}.
        /// </summary>
        public static string TicketActivityCreateOnBehalfOf {
            get {
                return ResourceManager.GetString("TicketActivityCreateOnBehalfOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a modified ticket.
        /// </summary>
        public static string TicketActivityEditTicketInfo {
            get {
                return ResourceManager.GetString("TicketActivityEditTicketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a closed the ticket by force.
        /// </summary>
        public static string TicketActivityForceClose {
            get {
                return ResourceManager.GetString("TicketActivityForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a has given up on the ticket.
        /// </summary>
        public static string TicketActivityGiveUp {
            get {
                return ResourceManager.GetString("TicketActivityGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a modified ticket attachments.
        /// </summary>
        public static string TicketActivityModifyAttachments {
            get {
                return ResourceManager.GetString("TicketActivityModifyAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a passed the ticket to {0}.
        /// </summary>
        public static string TicketActivityPass {
            get {
                return ResourceManager.GetString("TicketActivityPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  at a priority of {0}.
        /// </summary>
        public static string TicketActivityPriority {
            get {
                return ResourceManager.GetString("TicketActivityPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a and reactivated the ticket..
        /// </summary>
        public static string TicketActivityReactivate {
            get {
                return ResourceManager.GetString("TicketActivityReactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a reassigned the ticket to {0}.
        /// </summary>
        public static string TicketActivityReAssign {
            get {
                return ResourceManager.GetString("TicketActivityReAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a re-opened the ticket.
        /// </summary>
        public static string TicketActivityReOpen {
            get {
                return ResourceManager.GetString("TicketActivityReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a has requested more information.
        /// </summary>
        public static string TicketActivityRequestMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivityRequestMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a resolved the ticket.
        /// </summary>
        public static string TicketActivityResolve {
            get {
                return ResourceManager.GetString("TicketActivityResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a has provided more information.
        /// </summary>
        public static string TicketActivitySupplyMoreInfo {
            get {
                return ResourceManager.GetString("TicketActivitySupplyMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a has taken over the ticket.
        /// </summary>
        public static string TicketActivityTakeOver {
            get {
                return ResourceManager.GetString("TicketActivityTakeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Affects Customer.
        /// </summary>
        public static string TicketAffectsCustomer {
            get {
                return ResourceManager.GetString("TicketAffectsCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customer.
        /// </summary>
        public static string TicketAffectsCustomerShort {
            get {
                return ResourceManager.GetString("TicketAffectsCustomerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assigned To.
        /// </summary>
        public static string TicketAssignedTo {
            get {
                return ResourceManager.GetString("TicketAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assigned.
        /// </summary>
        public static string TicketAssignedToShort {
            get {
                return ResourceManager.GetString("TicketAssignedToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Category.
        /// </summary>
        public static string TicketCategory {
            get {
                return ResourceManager.GetString("TicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Category.
        /// </summary>
        public static string TicketCategoryShort {
            get {
                return ResourceManager.GetString("TicketCategoryShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created By.
        /// </summary>
        public static string TicketCreatedBy {
            get {
                return ResourceManager.GetString("TicketCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created By.
        /// </summary>
        public static string TicketCreatedByShort {
            get {
                return ResourceManager.GetString("TicketCreatedByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created Date.
        /// </summary>
        public static string TicketCreatedDate {
            get {
                return ResourceManager.GetString("TicketCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created Date.
        /// </summary>
        public static string TicketCreatedDateShort {
            get {
                return ResourceManager.GetString("TicketCreatedDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status Date.
        /// </summary>
        public static string TicketCurrentStatusDate {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status Date.
        /// </summary>
        public static string TicketCurrentStatusDateShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status By.
        /// </summary>
        public static string TicketCurrentStatusSetBy {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status By.
        /// </summary>
        public static string TicketCurrentStatusSetByShort {
            get {
                return ResourceManager.GetString("TicketCurrentStatusSetByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        public static string TicketDetails {
            get {
                return ResourceManager.GetString("TicketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        public static string TicketDetailsShort {
            get {
                return ResourceManager.GetString("TicketDetailsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Due Date.
        /// </summary>
        public static string TicketDueDate {
            get {
                return ResourceManager.GetString("TicketDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Due.
        /// </summary>
        public static string TicketDueDateShort {
            get {
                return ResourceManager.GetString("TicketDueDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Is Html.
        /// </summary>
        public static string TicketIsHtml {
            get {
                return ResourceManager.GetString("TicketIsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Is Html.
        /// </summary>
        public static string TicketIsHtmlShort {
            get {
                return ResourceManager.GetString("TicketIsHtmlShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updated By.
        /// </summary>
        public static string TicketLastUpdateBy {
            get {
                return ResourceManager.GetString("TicketLastUpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updated By.
        /// </summary>
        public static string TicketLastUpdateByShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateByShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updated Date.
        /// </summary>
        public static string TicketLastUpdateDate {
            get {
                return ResourceManager.GetString("TicketLastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updated Date.
        /// </summary>
        public static string TicketLastUpdateDateShort {
            get {
                return ResourceManager.GetString("TicketLastUpdateDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Owner.
        /// </summary>
        public static string TicketOwner {
            get {
                return ResourceManager.GetString("TicketOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Owner.
        /// </summary>
        public static string TicketOwnerShort {
            get {
                return ResourceManager.GetString("TicketOwnerShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Priority.
        /// </summary>
        public static string TicketPriority {
            get {
                return ResourceManager.GetString("TicketPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Priority.
        /// </summary>
        public static string TicketPriorityShort {
            get {
                return ResourceManager.GetString("TicketPriorityShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project.
        /// </summary>
        public static string TicketProject {
            get {
                return ResourceManager.GetString("TicketProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Project.
        /// </summary>
        public static string TicketProjectShort {
            get {
                return ResourceManager.GetString("TicketProjectShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Active.
        /// </summary>
        public static string TicketStatusActive {
            get {
                return ResourceManager.GetString("TicketStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closed.
        /// </summary>
        public static string TicketStatusClosed {
            get {
                return ResourceManager.GetString("TicketStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a More Info.
        /// </summary>
        public static string TicketStatusMoreInfo {
            get {
                return ResourceManager.GetString("TicketStatusMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolved.
        /// </summary>
        public static string TicketStatusResolved {
            get {
                return ResourceManager.GetString("TicketStatusResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tags.
        /// </summary>
        public static string TicketTagList {
            get {
                return ResourceManager.GetString("TicketTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tags.
        /// </summary>
        public static string TicketTagListShort {
            get {
                return ResourceManager.GetString("TicketTagListShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ticket Id.
        /// </summary>
        public static string TicketTicketId {
            get {
                return ResourceManager.GetString("TicketTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id.
        /// </summary>
        public static string TicketTicketIdShort {
            get {
                return ResourceManager.GetString("TicketTicketIdShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string TicketTicketStatus {
            get {
                return ResourceManager.GetString("TicketTicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string TicketTicketStatusShort {
            get {
                return ResourceManager.GetString("TicketTicketStatusShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        public static string TicketTicketType {
            get {
                return ResourceManager.GetString("TicketTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type.
        /// </summary>
        public static string TicketTicketTypeShort {
            get {
                return ResourceManager.GetString("TicketTicketTypeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title.
        /// </summary>
        public static string TicketTitle {
            get {
                return ResourceManager.GetString("TicketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title.
        /// </summary>
        public static string TicketTitleShort {
            get {
                return ResourceManager.GetString("TicketTitleShort", resourceCulture);
            }
        }
    }
}
