//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDesk.Localization.Views.Home {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketDesk.Localization.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;h3&gt;TD 2.5 Change List&lt;/h3&gt;
        ///        &lt;strong&gt;Feature Updates&lt;/strong&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;Online Setup (first-run-setup)&lt;/li&gt;
        ///            &lt;li&gt;Multiple Projects&lt;/li&gt;
        ///            &lt;li&gt;Multiple rich text editor options&lt;/li&gt;
        ///            &lt;li&gt;Responsive UI (small screen device support)&lt;/li&gt;
        ///        &lt;/ul&gt;
        ///        &lt;strong&gt;Technology Update&lt;/strong&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;Entity Framework 6x code-first&lt;/li&gt;
        ///            &lt;li&gt;MVC 5x - Razor View Engine&lt;/li&gt;
        ///            &lt;li&gt;Bootstrap 3&lt;/li&gt;
        ///    [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string ChangeList {
            get {
                return ResourceManager.GetString("ChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations! You appear to be running in Azure..
        /// </summary>
        public static string Congrat_Azure {
            get {
                return ResourceManager.GetString("Congrat_Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;img style=&quot;position: absolute; top: -20px; right: 0; border: 0;&quot; src=&quot;https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67&quot; alt=&quot;Fork me on GitHub&quot; data-canonical-src=&quot;https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png&quot;&gt;.
        /// </summary>
        public static string ForkMe {
            get {
                return ResourceManager.GetString("ForkMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p&gt;
        ///                    It has been a long road, but at last TicketDesk 2.5 is nearly ready for production use. The beta should be stable enough to evaluate and test. There are a number of rough edges still, but we are working hard to fix those up before the final release.
        ///                &lt;/p&gt;
        ///                &lt;div class=&quot;&quot;&gt;
        ///
        ///                    &lt;p&gt;Please keep the following in mind while evaluating the beta:&lt;/p&gt;
        ///                    &lt;ul class=&quot;text-muted&quot;&gt;
        ///                        &lt;li&gt;
        ///                 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Welcome to  TicketDesk 2.5 &lt;span class=&quot;small&quot;&gt;(beta)&lt;/span&gt;.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
